<a href="https://colab.research.google.com/github/tcsanitesh/DataScience/blob/main/CaseStudy1_Numpy_pandas_matplotlib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Extract data from the given SalaryGender CSV file and store the data from each
column in a separate NumPy array

In [75]:
import numpy as np
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/tcsanitesh/DataScience/main/SalaryGender.csv")

salary = np.array(df["Salary"])
gender = np.array(df["Gender"])
age = np.array(df["Age"])
phd = np.array(df["PhD"])
print(salary)
print(age)
print(gender)
print(phd)

[140.    30.    35.1   30.    80.    30.    60.    31.1  125.    51.
   3.    46.   150.     3.   130.    15.   130.    84.   190.    74.
  73.    10.    50.     7.     9.5   15.2   28.6   20.    72.    81.
 100.    90.    90.    35.    30.    25.    52.     9.    63.    72.
  16.    92.   106.     2.5    9.    32.    32.    55.    52.    28.
  20.    14.7   22.3   34.8   84.    19.   160.    65.    55.     4.6
 102.    20.    62.    55.    45.6   40.    24.    35.    48.    20.
  40.7   15.     0.25 152.    39.8   12.    30.   120.     1.7   36.
  96.    38.    90.     9.    25.8   22.    38.8   72.    89.    41.
  89.    25.    52.   115.    66.    18.6  152.     1.8   35.     4.  ]
[47 65 56 23 53 27 53 30 44 63 22 59 60 28 65 25 65 47 66 45 46 24 60 63
 27 66 36 30 51 65 45 52 54 30 52 26 49 22 34 60 28 58 77 67 27 48 45 49
 36 65 32 49 67 22 49 43 61 43 52 51 66 29 62 56 61 56 41 24 60 43 57 23
 53 71 20 27 69 58 37 32 33 32 60 71 30 62 54 42 62 51 71 29 55 54 55 26
 56 28 44 24]


. Find:
1. The number of men with a PhD
2. The number of women with a PhD

In [52]:
from numpy.lib.npyio import genfromtxt
import numpy as np
arr_np = genfromtxt("https://raw.githubusercontent.com/tcsanitesh/DataScience/main/SalaryGender.csv", delimiter =",")
#print(arr_np)
print(arr_np[:,0:1])
#np.savetxt("sal_gen_np.csv", arr_np, delimiter = ",")

[[   nan]
 [140.  ]
 [ 30.  ]
 [ 35.1 ]
 [ 30.  ]
 [ 80.  ]
 [ 30.  ]
 [ 60.  ]
 [ 31.1 ]
 [125.  ]
 [ 51.  ]
 [  3.  ]
 [ 46.  ]
 [150.  ]
 [  3.  ]
 [130.  ]
 [ 15.  ]
 [130.  ]
 [ 84.  ]
 [190.  ]
 [ 74.  ]
 [ 73.  ]
 [ 10.  ]
 [ 50.  ]
 [  7.  ]
 [  9.5 ]
 [ 15.2 ]
 [ 28.6 ]
 [ 20.  ]
 [ 72.  ]
 [ 81.  ]
 [100.  ]
 [ 90.  ]
 [ 90.  ]
 [ 35.  ]
 [ 30.  ]
 [ 25.  ]
 [ 52.  ]
 [  9.  ]
 [ 63.  ]
 [ 72.  ]
 [ 16.  ]
 [ 92.  ]
 [106.  ]
 [  2.5 ]
 [  9.  ]
 [ 32.  ]
 [ 32.  ]
 [ 55.  ]
 [ 52.  ]
 [ 28.  ]
 [ 20.  ]
 [ 14.7 ]
 [ 22.3 ]
 [ 34.8 ]
 [ 84.  ]
 [ 19.  ]
 [160.  ]
 [ 65.  ]
 [ 55.  ]
 [  4.6 ]
 [102.  ]
 [ 20.  ]
 [ 62.  ]
 [ 55.  ]
 [ 45.6 ]
 [ 40.  ]
 [ 24.  ]
 [ 35.  ]
 [ 48.  ]
 [ 20.  ]
 [ 40.7 ]
 [ 15.  ]
 [  0.25]
 [152.  ]
 [ 39.8 ]
 [ 12.  ]
 [ 30.  ]
 [120.  ]
 [  1.7 ]
 [ 36.  ]
 [ 96.  ]
 [ 38.  ]
 [ 90.  ]
 [  9.  ]
 [ 25.8 ]
 [ 22.  ]
 [ 38.8 ]
 [ 72.  ]
 [ 89.  ]
 [ 41.  ]
 [ 89.  ]
 [ 25.  ]
 [ 52.  ]
 [115.  ]
 [ 66.  ]
 [ 18.6 ]
 [152.  ]
 [  1.8 ]
 [ 35.  ]


In [ ]:
men_with_Phd = np.sum((phd == 1) & (gender == 1))
women_with_Phd = np.sum((phd == 1) & (gender == 0))

print("Men_with_Phd : ", men_with_Phd)
print("women_with_Phd : ", women_with_Phd)


Men_with_Phd :  24
women_with_Phd :  15


Calculate the total number of people who have a PhD degree from SalaryGender
CSV file.

In [64]:
df1 = df[["Age","PhD"]]
df1= df1[df1["PhD"] != 0 ]
#df1= df1.drop("PhD", axis=1 )
df1

Age  PhD
0    47    1
1    65    1
4    53    1
8    44    1
9    63    1
12   60    1
17   47    1
18   66    1
19   45    1
25   66    1
26   36    1
28   51    1
29   65    1
30   45    1
31   52    1
32   54    1
38   34    1
41   58    1
42   77    1
45   48    1
47   49    1
49   65    1
54   49    1
56   61    1
57   43    1
60   66    1
63   56    1
73   71    1
76   69    1
77   58    1
79   32    1
80   33    1
81   32    1
87   42    1
89   51    1
90   71    1
92   55    1
94   55    1
96   56    1

In [80]:
df = df[df['PhD']==1]
total_phd_count = df.shape[0]
print(total_phd_count)

39


How do you Count The Number Of Times Each Value Appears In An Array Of
Integers?
[0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9]
Answer should be array([4, 2, 1, 1, 3, 2, 0, 0, 0, 1]) which means 0 comes 4 times,
1 comes 2 times, 2 comes 1 time, 3 comes 1 time and so on.


In [87]:
from collections import Counter
import numpy as np

arr5 = [0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9]

counts = Counter(arr5)

# Create a NumPy array from the counts
result = np.array([counts[i] for i in range(max(arr5) + 1)])
print(result)

[4 2 1 1 3 2 0 0 0 1]


Create a numpy array [[0, 1, 2], [ 3, 4, 5], [ 6, 7, 8],[ 9, 10, 11]]) and filter the elements greater than 5.

In [4]:
import numpy as np
original_arr = np.array([[0, 1, 2], [ 3, 4, 5], [ 6, 7, 8],[ 9, 10, 11]])
print(original_arr)
filter_arr = original_arr[original_arr>5]
print(filter_arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 6  7  8  9 10 11]


Create a numpy array having NaN (Not a Number) and print it.
array([ nan, 1., 2., nan, 3., 4., 5.])
Print the same array omitting all elements which are nan

In [7]:
arr = np.array([ np.NaN, 1., 2., np.NaN, 3., 4., 5.])
print(arr)
filter_arr = arr[~np.isnan(arr)]
print(filter_arr)

[nan  1.  2. nan  3.  4.  5.]
[1. 2. 3. 4. 5.]


. Create a 10x10 array with random values and find the minimum and maximum
values.


In [13]:
random_arr =np.random.rand(10,10)
min_value = np.min(random_arr)
max_value = np.min(random_arr)
print(f"Random Array : {random_arr} with Min Num : {min_value} and Max Nm : {max_value}")

Random Array : [[0.83455634 0.65002925 0.59761219 0.82893238 0.70465515 0.4962792
  0.17974863 0.26170524 0.51989739 0.72710052]
 [0.04504802 0.07663224 0.14123697 0.32768896 0.03467042 0.85415859
  0.60065667 0.06894654 0.32852792 0.60377262]
 [0.1150017  0.45819497 0.25894008 0.25499868 0.51204974 0.56917539
  0.98792316 0.68703994 0.26410867 0.81081954]
 [0.0737999  0.0049511  0.99302696 0.69846197 0.7149102  0.88641315
  0.0969994  0.93274548 0.78163481 0.06713265]
 [0.38682959 0.59876048 0.14218582 0.93678082 0.85768019 0.21526064
  0.74184907 0.50591728 0.10198024 0.26580292]
 [0.0886991  0.45756223 0.28531688 0.32184473 0.89158289 0.39632348
  0.67733389 0.38221651 0.27288912 0.6523984 ]
 [0.63057403 0.64635473 0.94849639 0.61917239 0.2643419  0.95442573
  0.45591879 0.44071672 0.32728457 0.73083948]
 [0.79805484 0.67175623 0.68530264 0.21896045 0.87768244 0.85513799
  0.77833397 0.75466529 0.07983109 0.94226294]
 [0.05691584 0.0346408  0.38895509 0.73809792 0.21637749 0.5334125

Create a random vector of size 30 and find the mean value

In [15]:
random_arr =np.random.rand(30)
mean_value = np.mean(random_arr)
print(f"Random Array : {random_arr} with Mean Num : {mean_value} ")

Random Array : [0.59723968 0.71676023 0.63744931 0.70275294 0.02067814 0.43876819
 0.84343269 0.80220003 0.86727592 0.78587164 0.16826988 0.55618845
 0.65583108 0.26498988 0.43255022 0.22480576 0.40377854 0.22323185
 0.45675715 0.35277465 0.32184805 0.92362575 0.36622861 0.49439369
 0.65512117 0.87545169 0.25607604 0.82339654 0.51271741 0.05690638] with Mean Num : 0.5145790522618654 


Create numpy array having elements 0 to 10 And negate all the elements between
3 and 9


In [22]:
arr = np.arange(11)
arr[(arr>=3) & (arr<=9)]*= -1
arr

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8, -9, 10])

Create a random array of 3 rows and 3 columns and sort it according to 1st column, 2nd column or 3rd column.

In [27]:
random_arr = np.random.rand(3, 3)

sorted_by_1st_col = random_arr[random_arr[:, 0].argsort()]
sorted_by_2nd_col = random_arr[random_arr[:, 1].argsort()]
sorted_by_3rd_col = random_arr[random_arr[:, 2].argsort()]

print("\nSorted by 1st column:")
print(sorted_by_1st_col)

print("\nSorted by 2nd column:")
print(sorted_by_2nd_col)

print("\nSorted by 3rd column:")
print(sorted_by_3rd_col)


Sorted by 1st column:
[[0.04769939 0.43185564 0.85270607]
 [0.21858775 0.77540941 0.2303533 ]
 [0.83991163 0.07262342 0.52195666]]

Sorted by 2nd column:
[[0.83991163 0.07262342 0.52195666]
 [0.04769939 0.43185564 0.85270607]
 [0.21858775 0.77540941 0.2303533 ]]

Sorted by 3rd column:
[[0.21858775 0.77540941 0.2303533 ]
 [0.83991163 0.07262342 0.52195666]
 [0.04769939 0.43185564 0.85270607]]


Create a four dimensions array get sum over the last two axis at once.

Create a random array and swap two rows of an array.


Create a random matrix and Compute a matrix rank

Analyse various school outcomes in Tennessee using pandas. Suppose you are a
public school administrator. Some schools in your state of Tennessee are
performing below average academically. Your superintendent, under pressure
from frustrated parents and voters, approached you with the task of understanding
why these schools are under-performing. To improve school performance, you
need to learn more about these schools and their students, just as a business needs
to understand its own strengths and weaknesses and its customers. Though you is
eager to build an impressive explanatory model, you know the importance of
conducting preliminary research to prevent possible pitfalls or blind spots. Thus,
you engages in a thorough exploratory analysis, which includes: a lit review, data
collection, descriptive and inferential statistics, and data visualization.
Phase 1 - Data Collection
Here is a data of every public school in middle Tennessee. The data also includes
various demographic, school faculty, and income variables. You need to convert the
data into useful information.
• Read the data in pandas data frame
• Describe the data to find more details
Phase 2 - Group data by school ratings
Chooses indicators that describe the student body (for example, reduced_lunch) or
school administration (stu_teach_ratio) hoping they will
explain school_rating. reduced_lunch is a variable measuring the average percentage
of students per school enrolled in a federal program that provides lunches for students
from lower-income households. In short, reduced_lunch is a good proxy for household
income.
Module 4 – Introduction to NumPy, Pandas & Matplotlib
© B r a i n 4 c e E d u c a t i o n S o l u t i o n s P v t . L t d Page 3
Isolates ‘reduced_lunch’ and groups the data by ‘school_rating’ using pandas groupby
method and then uses describe on the re-shaped data
Phase 3 – Correlation analysis
Find the correlation between ‘reduced_lunch’ and ‘school_rating’. The values in the
correlation matrix table will be between -1 and 1. A value of -1 indicates the strongest
possible negative correlation, meaning as one variable decreases the other increases.
And a value of 1 indicates the opposite.
Phase 4 – Scatter Plot
Find the relationship between school_rating and reduced_lunch, Plot a graph with the
two variables on a scatter plot. Each dot represents a school. The placement of the dot
represents that school's rating (Y-axis) and the percentage of its students on reduced
lunch (x-axis). The downward trend line shows the negative correlation
between school_rating and reduced_lunch (as one increases, the other decreases). The
slope of the trend line indicates how much school_rating decreases
as reduced_lunch increases. A steeper slope would indicate that a small change
in reduced_lunch has a big impact on school_rating while a more horizontal slope
would indicate that the same small change in reduced_lunch has a smaller impact
on school_rating.
Phase 5 – Correlation Matrix
An efficient graph for assessing relationships is the correlation matrix, as seen below;
its color-coded cells make it easier to interpret than the tabular correlation matrix
above. Red cells indicate positive correlation; blue cells indicate negative correlation;
white cells indicate no correlation. The darker the colors, the stronger the correlation
(positive or negative) between those two variables. Draw a graph of correlation matrix
having all important fields of data frame.